name: Checks

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: checks_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Check Formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Lint styles
        run: pnpm lint:styles

      - name: Build
        run: pnpm build
